// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(public)/form_page.dart' as a0;
import 'app/(public)/home_page.dart' as a1;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/form',
        uri: Uri.parse('/form'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.FormPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  form: '/form',
  home: '/home',
);